'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''

def count_factors(n):
   factors = 0
   for i in range(1, n+1):
      if n % 2 == 0:
         factors += 1
   return factors

def triangle_num(n):
   return int(n*(n+1)/2)

for n in range(1,8000000,1):
   k = n // 2
   T_n = triangle_num(n)
   if n % 2:
      a, b = 2*k+1, k+1
   else:
      a, b = k, 2*k+1
   T_n_factors = count_factors(a)*count_factors(b)
   if T_n_factors >= 500:
      print(T_n, T_n_factors)
      break
   print(n, T_n, T_n_factors)
